services:
  sphinx-autobuild:
    container_name: sphinx-autobuild
    build:
      context: docker-sphinx-autobuild
    restart: always
    ports:
      - "8004:8000"
    volumes:
      - ./:/docs:delegated
